apiVersion: v1
user:
  #token: # JWT Token
  username: admin 
  password: Admin@2021
  #secret-id: # secret ID
  #secret-key: # secret Key
  client-certificate: /Users/yaoshuilin/iam/cert/admin.pem 
  client-key: /Users/yaoshuilin/iam/cert/admin-key.pem  
  #client-certificate-data:
  #client-key-data:

server:
  address: https://127.0.0.1:8443 # iam api-server address
  timeout: 10s 
  #max-retries: # default 0
  #retry-interval: # default 1s
  #tls-server-name: # TLS server name
  #insecure-skip-tls-verify: # Set to true to skip TLS secure authentication mode, which will make HTTPS connections insecure
  certificate-authority: /Users/yaoshuilin/iam/etc/iam/cert/ca.pem  # The path to the cert file for CA authorization.
  #certificate-authority-data:
